-keep class com.google.crypto.tink.proto.** { *; }
-keep class com.google.crypto.tink.shaded.protobuf.** { *; }
-keep class androidx.security.** { *; }
-keepclassmembers class androidx.security.** { *; }